Repository GreenSpark-greenspark/greenspark-backend, pull requests merged in 2024-12, with the labels that each got.

#58 feat: 퀴즈 api 구현
  src/main/java/GreenSpark/greenspark/OAuth/CustomSuccessHandler.java
  src/main/java/GreenSpark/greenspark/config/SecurityConfig.java
  src/main/java/GreenSpark/greenspark/controller/AppliancesController.java
  src/main/java/GreenSpark/greenspark/controller/QuizController.java
  src/main/java/GreenSpark/greenspark/controller/ReissueController.java
  src/main/java/GreenSpark/greenspark/controller/UserController.java
  src/main/java/GreenSpark/greenspark/domain/Quiz.java
  src/main/java/GreenSpark/greenspark/domain/UserDailyQuiz.java
  src/main/java/GreenSpark/greenspark/domain/UserQuizRecord.java
  src/main/java/GreenSpark/greenspark/dto/QuizResultDto.java
  src/main/java/GreenSpark/greenspark/dto/QuizWithSolvedDto.java
  src/main/java/GreenSpark/greenspark/jwt/JWTFilter.java
  src/main/java/GreenSpark/greenspark/repository/QuizRepository.java
  src/main/java/GreenSpark/greenspark/repository/UserDailyQuizRepository.java
  src/main/java/GreenSpark/greenspark/repository/UserQuizRecordRepository.java
  src/main/java/GreenSpark/greenspark/service/QuizService.java
  src/main/resources/application.yml
Labels: fix, feature

#60 fix: Appliancescontroller 내 가전제품 상세보기 api access 토큰 추가
  src/main/java/GreenSpark/greenspark/controller/AppliancesController.java
Labels: fix

#61 feat: 가전제품 메모 api 구현
  src/main/java/GreenSpark/greenspark/controller/AppliancesController.java
  src/main/java/GreenSpark/greenspark/controller/MemoController.java
  src/main/java/GreenSpark/greenspark/domain/Memo.java
  src/main/java/GreenSpark/greenspark/dto/MemoDto.java
  src/main/java/GreenSpark/greenspark/repository/MemoRepository.java
Labels: feature

#64 feat: 유저정보 db에 있는지 확인 api 구현
  src/main/java/GreenSpark/greenspark/controller/UserController.java
Labels: feature

#66 fix: fix: 로그인 reissue, access 수정
  src/main/java/GreenSpark/greenspark/OAuth/CustomSuccessHandler.java
  src/main/java/GreenSpark/greenspark/controller/ReissueController.java
  src/main/java/GreenSpark/greenspark/jwt/JWTFilter.java
Labels: fix

#68 feat: 마이페이지 api 구현
  src/main/java/GreenSpark/greenspark/controller/UserController.java
  src/main/java/GreenSpark/greenspark/dto/UserInfoDto.java
Labels: feature

#71 feat: 에너지 퀴즈 스케줄링 및 중복 제출 처리
  src/main/java/GreenSpark/greenspark/GreensparkApplication.java
  src/main/java/GreenSpark/greenspark/config/SchedulingConfig.java
  src/main/java/GreenSpark/greenspark/controller/QuizController.java
  src/main/java/GreenSpark/greenspark/repository/UserDailyQuizRepository.java
  src/main/java/GreenSpark/greenspark/repository/UserQuizRecordRepository.java
  src/main/java/GreenSpark/greenspark/service/QuizService.java
  src/main/resources/application.yml
Labels: feature

#73 feat: 메모 update 구현
  src/main/java/GreenSpark/greenspark/controller/MemoController.java
  src/main/java/GreenSpark/greenspark/repository/MemoRepository.java
Labels: feature

#76 feat: 출석체크 API
  src/main/java/GreenSpark/greenspark/controller/UserController.java
  src/main/java/GreenSpark/greenspark/domain/User.java
  src/main/java/GreenSpark/greenspark/repository/UserRepository.java
  src/main/java/GreenSpark/greenspark/service/UserService.java
Labels: feature

#78 feat: 가전제품 히스토리 수정
  src/main/java/GreenSpark/greenspark/controller/AppliancesController.java
  src/main/java/GreenSpark/greenspark/domain/ApplianceHistory.java
  src/main/java/GreenSpark/greenspark/dto/ApplianceDto.java
  src/main/java/GreenSpark/greenspark/repository/ApplianceHistoryRepository.java
  src/main/java/GreenSpark/greenspark/service/AppliancesService.java
Labels: feature

#80 feat: 최종 로그인 로직 및 cors 수정
  src/main/java/GreenSpark/greenspark/OAuth/CustomSuccessHandler.java
  src/main/java/GreenSpark/greenspark/config/SecurityConfig.java
  src/main/java/GreenSpark/greenspark/config/WebConfig.java
  src/main/java/GreenSpark/greenspark/controller/ReissueController.java
  src/main/java/GreenSpark/greenspark/domain/User.java
  src/main/java/GreenSpark/greenspark/service/CustomOAuth2UserService.java
  src/main/resources/application.yml
Labels: feature
